# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='members',
        ),
        migrations.AddField(
            model_name='groupusers',
            name='ingroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.ProjectGroup'),
        ),
    ]
