# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0002_auto_20170605_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupUsers',
            new_name='GroupUser',
        ),
    ]
