# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripPlanner', '0003_auto_20170605_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forProject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.ProjectGroup')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.ProjectHost')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopicDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='pref',
        ),
        migrations.AddField(
            model_name='question',
            name='forTopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Topic'),
        ),
        migrations.AddField(
            model_name='preference',
            name='forTopicDatabase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.TopicDatabase'),
        ),
        migrations.AddField(
            model_name='preference',
            name='groupUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.GroupUser'),
        ),
        migrations.AddField(
            model_name='preference',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='forQuestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Question'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='inTopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Topic'),
        ),
    ]
